var trinket =
[
    //#region PLAYER'S HANDBOOK
        `Mummified goblin hand`,
        `Piece of crystal*`,
        `Gold coin minted in an unknown land`,
        `Diary written in a language you don't know`,
        `Brass ring*`,
        `Old chess piece made from glass`,
        `Pair of knucklebone dice, each with a skull symbol on the side that would normally show six pips`,
        `Small idol depicting a nightmarish creature*`,
        `Rope necklace from which dangles four mummified elf fingers`,
        `Deed for a parcel of land in a realm unknown to you`,
        `1-ounce block made from an unknown material`,
        `Small cloth doll skewered with needles`,
        `Tooth from an unknown beast`,
        `Enormous scale, perhaps from a dragon`,
        `Bright green feather`,
        `Old divination card bearing your likeness`,
        `Glass orb filled with moving smoke`,
        `1-pound egg with a bright red shell`,
        `Tobacco pipe*`,
        `Glass jar containing a weird bit of flesh floating in pickling fluid`,
        `Tiny dwemer-crafted music box*`,
        `Small wooden statuette of a smug bosmer`,
        `Brass orb etched with strange runes`,
        `Multicolored stone disk`,
        `Tiny silver icon of a raven`,
        `Bag containing forty-seven humanoid teeth*`,
        `Shard of obsidian*`,
        `Reptile's bony talon hanging from a plain leather necklace`,
        `Pair of old socks`,
        `Blank book*`,
        `Silver badge in the shape of a five-pointed star`,
        `Familiar knife*`,
        `Glass vial filled with nail clippings`,
        `Rectangular metal device with two tiny metal cups on one end*`,
        `White, sequined glove sized for a human`,
        `Vest with one hundred tiny pockets`,
        `Small, weightless stone block`,
        `Tiny sketch portrait of a goblin`,
        `Empty glass vial*`,
        `Lump of coal*`,
        `Scrap of cloth from an old banner`,
        `Rank insignia from a lost legionnaire`,
        `Tiny silver bell without a clapper`,
        `Mechanical canary inside a dwemer lamp`,
        `Tiny chest carved to look like it has numerous feet on the bottom`,
        `Dead nixad inside a clear glass bottle`,
        //`Metal can that has no opening but sounds as if it is filled with liquid, sand, spiders, or broken glass (your choice)`,
        `A glass orb filled with water, in which swims a clockwork goldfish`,
        `A silver spoon with an 'M' engraved on the handle`,
        `A whistle made from gold-colored wood`,
        `A dead scarab beetle the size of your hand`,
        `Two toy soldiers, one with a missing head`,
        `A small box filled with different-sized buttons`,
        `A candle that can't be lit`,
        `A tiny cage with no door`,
        `An old key`,
        `An indecipherable treasure map`,
        `A hilt from a broken sword`,
        `A rabbit's foot`,
        `A glass eye`,
        `A cameo carved in the likeness of a hideous person`,
        `A silver skull the size of a coin`,
        `An alabaster mask`,
        `A pyramid of sticky black incense that smells very bad`,
        `A nightcap that, when worn, gives you pleasant dreams`,
        `A single caltrop made from bone`,
        `A gold monocle frame without the lens`,
        `A 1-inch cube, each side painted a different color`,
        `A crystal knob from a door`,
        `A small packet filled with pink dust`,
        `A fragment of a beautiful song, written as musical notes on two pieces of parchment`,
        `A silver teardrop earring made from a real teardrop`,
        `The shell of an egg painted with scenes of human misery in disturbing detail`,
        `A fan that, when unfolded, shows a sleeping cat`,
        `A set of bone pipes`,
        `A four-leaf clover pressed inside a book discussing manners and etiquette`,
        `A sheet of parchment upon which is drawn a complex mechanical contraption`,
        `An ornate scabbard that fits no blade you have found so far`,
        `An invitation to a party where a murder happened`,
        `A bronze pentacle with an etching of a rat's head in its center`,
        `A purple handkerchief embroidered with the name of a powerful archmage`,
        `Half of a floorplan for a temple, castle, or some other structure`,
        `A bit of folded cloth that, when unfolded, turns into a stylish cap`,
        `A receipt of deposit at a bank in a far-flung city`,
        `A diary with seven missing pages`,
        `An empty silver snuffbox bearing an inscription on the surface that says "dreams"`,
        `An iron holy symbol devoted to an unknown god`,
        `A book that tells the story of a legendary hero's rise and fall, with the last chapter missing`,
        `A vial of dragon blood`,
        `An ancient arrow of elven design`,
        `A needle that never bends`,
        `An ornate brooch of dwarven design`,
        `An empty wine bottle bearing a pretty label that says, "The Wizard of Wines Winery, Red Dragon Crush, 331422-W"`,
        `A mosaic tile with a multicolored, glazed surface`,
        `A petrified mouse`,
        `A black pirate flag adorned with a dragon's skull and crossbones`,
        `A tiny mechanical crab or spider that moves about when it's not being observed`,
        `A glass jar containing lard with a label that reads, "Griffon Grease"`,
        `A wooden box with a ceramic bottom that holds a living worm with a head on each end of its body`,
        `A metal urn containing the ashes of a hero`,
    //#endregion
]