const stratagems = [

  // Offense Stratagems
  { type: 'Offense', name: 'Orbital Precision Strike' },
  { type: 'Offense', name: 'Orbital Gatling Barrage' },
  { type: 'Offense', name: 'Orbital Airburst Strike' },
  { type: 'Offense', name: 'Orbital Napalm Barrage' },
  { type: 'Offense', name: 'Orbital 120mm HE Barrage' },
  { type: 'Offense', name: 'Orbital Walking Barrage' },
  { type: 'Offense', name: 'Orbital 380mm HE Barrage' },
  { type: 'Offense', name: 'Orbital Railcannon Strike' },
  { type: 'Offense', name: 'Orbital Laser' },
  { type: 'Offense', name: 'Orbital EMS Strike' },
  { type: 'Offense', name: 'Orbital Gas Strike' },
  { type: 'Offense', name: 'Orbital Smoke Strike' },
  { type: 'Offense', name: 'Eagle 500kg Bomb' },
  { type: 'Offense', name: 'Eagle Strafing Run' },
  { type: 'Offense', name: 'Eagle 110mm Rocket Pods' },
  { type: 'Offense', name: 'Eagle Airstrike' },
  { type: 'Offense', name: 'Eagle Cluster Bomb' },
  { type: 'Offense', name: 'Eagle Napalm Airstrike' },
  { type: 'Offense', name: 'Eagle Smoke Strike' },

  // Support Stratagems
  { type: 'Weaponry', name: 'MG-43 Machine Gun' },
  { type: 'Weaponry', name: 'M-105 Stalwart' },
  { type: 'Weaponry', name: 'MG-206 Heavy Machine Gun' },
  { type: 'Weaponry', name: 'RS-422 Railgun' },
  { type: 'Weaponry', name: 'APW-1 Anti-Materiel Rifle' },
  { type: 'Weaponry', name: 'GL-21 Grenade Launcher' },
  { type: 'Weaponry', name: 'TX-41 Sterilizer' },
  { type: 'Weaponry', name: 'FLAM-40 Flamethrower' },
  { type: 'Weaponry', name: 'LAS-98 Laser Cannon' },
  { type: 'Weaponry', name: 'LAS-99 Quasar Cannon' },
  { type: 'Weaponry', name: 'ARC-3 Arc Thrower' },
  { type: 'Weaponry', name: 'MLS-4X Commando' },
  { type: 'Weaponry', name: 'EAT-17 Expendable Anti-Tank' },
  { type: 'Ammopack', name: 'AC-8 Autocannon' },
  { type: 'Ammopack', name: 'RL-77 Airburst Rocket Launcher' },
  { type: 'Ammopack', name: 'FAF-14 Spear' },
  { type: 'Ammopack', name: 'StA-X3 W.A.S.P. Launcher' },
  { type: 'Ammopack', name: 'GR-8 Recoilless Rifle' },
  { type: 'Backpack', name: 'SH-32 Shield Generator Pack' },
  { type: 'Backpack', name: 'SH-51 Directional Shield' },
  { type: 'Backpack', name: 'SH-20 Ballistic Shield Backpack' },
  { type: 'Backpack', name: 'LIFT-860 Hover Pack' },
  { type: 'Backpack', name: 'B-1 Supply Pack' },
  { type: 'Backpack', name: 'B-100 Portable Hellbomb' },
  { type: 'Backpack', name: 'LIFT-850 Jump Pack' },
  { type: 'Backpack', name: "AX/AR-23 'Guard Dog'" },
  { type: 'Backpack', name: "AX/LAS-5 'Guard Dog' Rover" },
  { type: 'Backpack', name: "AX/TX-13 'Guard Dog' Dog Breath" },
  { type: 'Mechanic', name: 'M-102 Fast Recon Vehicle' },
  { type: 'Mechanic', name: 'EXO-49 Emancipator Exosuit' },
  { type: 'Mechanic', name: 'EXO-45 Patriot Exosuit' },
  // { type: 'Weaponry', name: 'CQC-1 One True Flag' },

  // Defense Stratagems
  { type: 'Defense', name: 'A/G-16 Gatling Sentry' },
  { type: 'Defense', name: 'A/MG-43 Machine Gun Sentry' },
  { type: 'Defense', name: 'A/FLAM-40 Flame Sentry' },
  { type: 'Defense', name: 'A/MLS-4X Rocket Sentry' },
  { type: 'Defense', name: 'A/AC-8 Autocannon Sentry' },
  { type: 'Defense', name: 'A/M-23 EMS Mortar Sentry' },
  { type: 'Defense', name: 'A/M-12 Mortar Sentry' },
  { type: 'Defense', name: 'FX-12 Shield Generator Relay' },
  { type: 'Defense', name: 'E/GL-21 Grenadier Battlement' },
  { type: 'Defense', name: 'E/AT-12 Anti-Tank Emplacement' },
  { type: 'Defense', name: 'E/MG-101 HMG Emplacement' },
  { type: 'Defense', name: 'A/ARC-3 Tesla Tower' },
  { type: 'Defense', name: 'MD-17 Anti-Tank Mines' },
  { type: 'Defense', name: 'MD-8 Gas Mines' },
  { type: 'Defense', name: 'MD-6 Anti-Personnel Minefield' },
  { type: 'Defense', name: 'MD-I4 Incendiary Mines' },
  
];

// { type: '', name: '' },